# Python Programming with Numpy 

## Introduction

This lab will focus on the widely-used library Numpy, which provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy. In such case, we also recommend the numpy for [Matlab users page](https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html).

In detail, we will cover the usage of Arrays, Array indexing, Datatypes, Array math, Broadcasting, etc. in this tutorial.

Note: Before reading this tutorial you should know a bit of Python. If you would like to refresh your memory, take a look at Python_01_Basic.

If you wish to work the examples in this tutorial, you must also have some software installed on your computer. Please click [here](http://scipy.org/install.html) for instructions or find some references from Lab 1.

## Numpy

*NumPy is the fundamental library for scientific computing with Python. NumPy is centered around a powerful N-dimensional array object, and it also contains useful linear algebra, Fourier transform, and random number functions.*


To use Numpy, we first need to import the `numpy` package:

In [ ]:
import numpy as np

### Creating arrays

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.

For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In the example pictured below, the array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 2, the second dimension has a length of 3.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

## `np.zeros`
The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [ ]:
np.zeros(5)

It's just as easy to create a 2D array (ie. a matrix) by providing a tuple with the desired number of rows and columns. For example, here's a 3x4 matrix:

In [ ]:
np.zeros((3,4))

## Some vocabulary

* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**. (This is different to the matrx rank in math)
    * For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the above matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)

In [ ]:
a = np.zeros((3,4))
a

In [ ]:
a.shape

In [ ]:
a.ndim  # equal to len(a.shape)

In [ ]:
a.size

## N-dimensional arrays
You can also create an N-dimensional array of arbitrary rank. For example, here's a 3D array (rank=3), with shape `(2,3,4)`:

In [ ]:
np.zeros((2,3,4))

## Array type
NumPy arrays have the type `ndarray`s:

In [ ]:
type(np.zeros((3,4)))

## `np.ones`
Many other NumPy functions create `ndarrays`.

Here's a 3x4 matrix full of ones:

In [ ]:
np.ones((3,4))

## `np.full`
Creates an array of the given shape initialized with the given value. Here's a 3x4 matrix full of `π`.

In [ ]:
np.full((3,4), np.pi)

##  `np.eye`

Creates an array as a identity matrix, the element value of the diagonal is 1.

In [ ]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

## np.array
Of course you can initialize an `ndarray` using a regular python array. Just call the `array` function:

In [ ]:
np.array([[1,2,3,4], [10, 20, 30, 40]])

## `np.arange`
You can create an `ndarray` using NumPy's `range` function, which is similar to python's built-in `range` function:

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists. For example:

In [ ]:
np.arange(1, 5)

It also works with floats:

In [ ]:
np.arange(1.0, 5.0)

Of course you can provide a step parameter:

In [ ]:
np.arange(1, 5, 0.5)

However, when dealing with floats, the exact number of elements in the array is not always predictible. For example, consider this:

In [ ]:
print(np.arange(0, 5/3, 1/3)) # depending on floating point errors, the max value is 4/3 or 5/3.
print(np.arange(0, 5/3, 0.333333333))
print(np.arange(0, 5/3, 0.333333334))


## `np.linspace`
For this reason, it is generally preferable to use the `linspace` function instead of `arange` when working with floats. The `linspace` function returns an array containing a specific number of points evenly distributed between two values (note that the maximum value is *included*, contrary to `arange`):

In [ ]:
print(np.linspace(0, 5/3, 6))

## `np.random.rand` and `np.random.randn`
A number of functions are available in NumPy's `random` module to create `ndarray`s initialized with random values.
the input parameters are `d0, d1, ..., dn`.

For example, here is a 3x4 matrix initialized with random floats between 0 and 1 (uniform distribution):

In [ ]:
np.random.rand(3,4)

In [ ]:
np.random.rand(2,3,4)

Here's a 3x4 matrix containing random floats sampled from a univariate [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) (Gaussian distribution) of mean 0 and variance 1:

In [ ]:
np.random.randn(3,4)

To give you a feel of what these distributions look like, let's use matplotlib (see the [matplotlib tutorial](tools_matplotlib.ipynb) for more details):

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
plt.hist(np.random.rand(100000), normed=True, bins=100, histtype="step", color="blue", label="rand")
plt.hist(np.random.randn(100000), normed=True, bins=100, histtype="step", color="red", label="randn")
plt.axis([-2.5, 2.5, 0, 1.1])
plt.legend(loc = "upper left")
plt.title("Random distributions")
plt.xlabel("Value")
plt.ylabel("Density")
plt.show()

## `np.random.random` 
Return random floats in the half-open interval $[0.0, 1.0)$

The main difference is the input should be `size`.


In [ ]:
np.random.random((2,2))  # Create an array filled with random values

In [ ]:
np.random.random((2,3,4)

##  `np.random.randint`
Return random integers from low (inclusive) to high (exclusive). 
Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval $[low, high)$. 
If high is None (the default), then results are from $[0, low)$.
```numpy.random.randint(low, high=None, size=None, dtype='l')```

In [ ]:
np.random.randint(2, size=10)

In [ ]:
np.random.randint(5, size=(2, 4))

In [ ]:
np.random.randint(10, 20, size=(2, 4))

## `np.fromfunction`
Construct an array by executing a function over each coordinate.
You can also initialize an `ndarray` using a function:
```numpy.fromfunction(function, shape, **kwargs)```
The resulting array therefore has a value $f_n(x, y, z)$ at coordinate $(x, y, z)$.

In [ ]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

In [ ]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

In [ ]:
def my_function(z, y, x):
    return x * y + z

np.fromfunction(my_function, (3, 2, 10))

NumPy first creates three `ndarrays` (one per dimension), each of shape `(2, 10)`. Each array has values equal to the coordinate along a specific axis. For example, all elements in the `z` array are equal to their z-coordinate:

    [[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
      [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
    
     [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
      [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
    
     [[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
      [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]]

So the terms x, y and z in the expression `x * y + z` above are in fact `ndarray`s (we will discuss arithmetic operations on arrays below).  The point is that the function `my_function` is only called *once*, instead of once per element. This makes initialization very efficient.

### Array Attributes

NumPy’s array class is called ndarray and the more important attributes of an ndarray object are:

ndarray.ndim: the number of axes (dimensions) of the array. 

ndarray.shape: the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.

ndarray.size: the total number of elements of the array. 

ndarray.dtype: an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

Here are some instances for the usage of 'ndarray.ndim', 'ndarray.shape', 'ndarray.size', and 'ndarray.dtype'.

## `dtype`
NumPy's `ndarray`s are also efficient in part because all their elements must have the same type (usually numbers).
You can check what the data type is by looking at the `dtype` attribute:

In [ ]:
c = np.arange(1, 5)
print(c.dtype, c)

In [ ]:
c = np.arange(1.0, 5.0)
print(c.dtype, c)

Instead of letting NumPy guess what data type to use, you can set it explicitly when creating an array by setting the `dtype` parameter:

In [ ]:
d = np.arange(1, 5, dtype=np.complex64)
print(d.dtype, d)

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

In [ ]:
x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

In [ ]:
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html). Also, you can read about other methods of array creation [in the tutorial](https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

Available data types include `int8`, `int16`, `int32`, `int64`, `uint8`|`16`|`32`|`64`, `float16`|`32`|`64` and `complex64`|`128`. Check out [the documentation](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html) for the full list.

## `itemsize`
The `itemsize` attribute returns the size (in bytes) of each item:

In [ ]:
e = np.arange(1, 5, dtype=np.complex64)
e.itemsize

In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print (a)

In [ ]:
a.shape # should return (3,5)

In [ ]:
a.size  # should return 15

In [ ]:
a.ndim  # should return 2

In [ ]:
a.dtype # return 'int64'

## `data` buffer
An array's data is actually stored in memory as a flat (one dimensional) byte buffer. It is available *via* the `data` attribute (you will rarely need it, though).

In [ ]:
f = np.array([[1,2],[1000, 2000]], dtype=np.int32)
f.data

In python 2, `f.data` is a buffer. In python 3, it is a memoryview.

In [ ]:
if (hasattr(f.data, "tobytes")):
    data_bytes = f.data.tobytes() # python 3
else:
    data_bytes = memoryview(f.data).tobytes() # python 2

data_bytes

Several `ndarrays` can share the same data buffer, meaning that modifying one will also modify the others. We will see an example in a minute.

# Reshaping an array
## In place
Changing the shape of an `ndarray` is as simple as setting its `shape` attribute. However, the array's size must remain the same.

In [ ]:
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

In [ ]:
g.shape = (6, 4)
print(g)
print("Rank:", g.ndim)

In [ ]:
g.shape = (2, 3, 4)
print(g)
print("Rank:", g.ndim)

## `ravel`
Finally, the `ravel` function returns a new one-dimensional `ndarray` that also points to the same data:
It is equivalent to `reshape(-1, order=order)`. 
`numpy.ravel(a, order='C')`

**order** : {‘C’,’F’, ...}, optional. The elements of a are read using this index order. ‘C’ means to index the elements in row-major, ‘F’ means to index the elements in column-major

In [ ]:
g.ravel()

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

In [ ]:
print(np.ravel(x))

In [ ]:
print(np.ravel(x, order = 'C')) 

In [ ]:
 print(np.ravel(x, order='F'))

## `reshape`
The `reshape` function returns a new `ndarray` object pointing at the **same** data. This means that modifying one array will also modify the other.

In [ ]:
g = np.arange(24)
g2 = g.reshape(4,6)
print(g2)
print("Rank:", g2.ndim)

Set item at row 1, col 2 to 999 (more about indexing below).

In [ ]:
g2[1, 2] = 999
g2

The corresponding element in `g` has been modified.

In [ ]:
g

# Array indexing
## One-dimensional arrays
One-dimensional NumPy arrays can be accessed more or less like regular python arrays:

In [ ]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[3]

In [ ]:
a[2:5]

In [ ]:
a[2:-1]

In [ ]:
a[:2]

In [ ]:
a[2::2]

In [ ]:
a[::-1]

You can also modify an `ndarray` slice:

In [ ]:
a[2:5] = [997, 998, 999]
a

Of course, you can modify elements:

In [ ]:
a[3]=999
a

## Differences with regular python arrays
Contrary to regular python arrays, if you assign a single value to an `ndarray` slice, it is copied across the whole slice, thanks to broadcasting rules discussed above.

In [ ]:
a[2:5] = -1
a

Also, you cannot grow or shrink `ndarray`s this way:

In [ ]:
try:
    a[2:5] = [1,2,3,4,5,6]  # too long
except ValueError as e:
    print(e)

You cannot delete elements either:

In [ ]:
try:
    del a[2:5]
except ValueError as e:
    print(e)

Last but not least, `ndarray` **slices are actually *views*** on the same data buffer. This means that if you create a slice and modify it, you are actually going to modify the original `ndarray` as well!

In [ ]:
a_slice = a[2:6]
a_slice[1] = 1000
a  # the original array was modified!

In [ ]:
a[3] = 2000
a_slice  # similarly, modifying the original array modifies the slice!

If you want a copy of the data, you need to use the `copy` method:

In [ ]:
another_slice = a[2:6].copy()
another_slice[1] = 3000
a  # the original array is untouched

In [ ]:
a[3] = 4000
another_slice  # similary, modifying the original array does not affect the slice copy

## Multi-dimensional arrays
Multi-dimensional arrays can be accessed in a similar way by providing an index or slice for each axis, separated by commas:

In [ ]:
b = np.arange(48).reshape(4, 12)
b

In [ ]:
b[1, 2]  # row 1, col 2

In [ ]:
b[1, :]  # row 1, all columns

In [ ]:
b[:, 1]  # all rows, column 1

**Caution**: 
***note the subtle difference between these two expressions: ***

In [ ]:
b[1, :]

In [ ]:
b[1:2, :]

The first expression returns row 1 as a 1D array of shape `(12,)`, while the second returns that same row as a 2D array of shape `(1, 12)`.

## Fancy indexing
You may also specify a list of indices that you are interested in. This is referred to as *fancy indexing*.

In [ ]:
b[(0,2), 2:5]  # rows 0 and 2, columns 2 to 4 (5-1)

In [ ]:
b[:, (-1, 2, -1)]  # all rows, columns -1 (last), 2 and -1 (again, and in this order)

If you provide multiple index arrays, you get a 1D `ndarray` containing the values of the elements at the specified coordinates.

In [ ]:
b[(-1, 2, -1, 2), (5, 9, 1, 9)]  # returns a 1D array with b[-1, 5], b[2, 9], b[-1, 1] and b[2, 9] (again)

## Higher dimensions
Everything works just as well with higher dimensional arrays, but it's useful to look at a few examples:

In [ ]:
c = b.reshape(4,2,6)
c

In [ ]:
c[2, 1, 4]  # matrix 2, row 1, col 4

In [ ]:
c[2, :, 3]  # matrix 2, all rows, col 3

If you omit coordinates for some axes, then all elements in these axes are returned:

In [ ]:
c[2, 1]  # Return matrix 2, row 1, all columns.  This is equivalent to c[2, 1, :]

## Ellipsis (`...`)
You may also write an ellipsis (`...`) to ask that all non-specified axes be entirely included.

In [ ]:
c[2, ...]  #  matrix 2, all rows, all columns.  This is equivalent to c[2, :, :]

In [ ]:
c[2, 1, ...]  # matrix 2, row 1, all columns.  This is equivalent to c[2, 1, :]

In [ ]:
c[2, ..., 3]  # matrix 2, all rows, column 3.  This is equivalent to c[2, :, 3]

In [ ]:
c[..., 3]  # all matrices, all rows, column 3.  This is equivalent to c[:, :, 3]

## Boolean indexing
You can also provide an `ndarray` of boolean values on one axis to specify the indices that you want to access.

In [ ]:
b = np.arange(48).reshape(4, 12)
b

In [ ]:
rows_on = np.array([True, False, True, False])
b[rows_on, :]  # Rows 0 and 2, all columns. Equivalent to b[(0, 2), :]

In [ ]:
cols_on = np.array([False, True, False] * 4)
b[:, cols_on]  # All rows, columns 1, 4, 7 and 10

## `np.ix_`
You cannot use boolean indexing this way on multiple axes, but you can work around this by using the `ix_` function:

In [ ]:
b[np.ix_(rows_on, cols_on)]

In [ ]:
np.ix_(rows_on, cols_on)

If you use a boolean array that has the same shape as the `ndarray`, then you get in return a 1D array containing all the values that have `True` at their coordinate. This is generally used along with conditional operators:

In [ ]:
b[b % 3 == 1]

# Iterating
Iterating over `ndarray`s is very similar to iterating over regular python arrays. Note that iterating over multidimensional arrays is done with respect to the first axis.

In [ ]:
c = np.arange(24).reshape(2, 3, 4)  # A 3D array (composed of two 3x4 matrices)
c

In [ ]:
for m in c:
    print("Item:")
    print(m)

In [ ]:
for i in range(len(c)):  # Note that len(c) == c.shape[0]
    print("Item:")
    print(c[i])

If you want to iterate on *all* elements in the `ndarray`, simply iterate over the `flat` attribute:

In [ ]:
for i in c.flat:
    print("Item:", i)

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]

                     #          [ True  True]]"

We use boolean array indexing to construct a rank 1 array consisting of the elements of a corresponding to the True values of bool_idx

In [ ]:
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

One more example to help you understand the indexing. Try the following commands and see the results

In [ ]:
a = np.arange(10)**3
print(a)

In [ ]:
a[2]

In [ ]:
a[2:5]

In [ ]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
print(a)

In [ ]:
a[ : :-1]   # reversed a

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should [read the documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas. For example:

In [ ]:
b = np.arange(15).reshape(3, 5)
b

In [ ]:
b[2,3]                         # select the element in the third row and fourth column of b

In [ ]:
b[0:5, 1]                       # each row in the second column of b

In [ ]:
b[ : ,1]                        # equivalent to the previous example

In [ ]:
b[1:3, : ]                      # each column in the second and third row of b

# Arithmetic operations
All the usual arithmetic operators (`+`, `-`, `*`, `/`, `//`, `**`, etc.) can be used with `ndarray`s. They apply *elementwise*:

Note that the multiplication is *not* a matrix multiplication. We will discuss matrix operations below.

The arrays must have the same shape. If they do not, NumPy will apply the *broadcasting rules*.

In [ ]:
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])
print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a // b  =", a // b)
print("a % b  =", a % b)
print("a ** b =", a ** b)

Note that the multiplication is *not* a matrix multiplication. We will discuss matrix operations below.

The arrays must have the same shape. If they do not, NumPy will apply the *broadcasting rules*.

# Broadcasting

In general, when NumPy expects arrays of the same shape but finds that this is not the case, it applies the so-called *broadcasting* rules:

## First rule
*If the arrays do not have the same rank, then a 1 will be prepended to the smaller ranking arrays until their ranks match.*

In [ ]:
h = np.arange(5).reshape(1, 1, 5)
h

Now let's try to add a 1D array of shape `(5,)` to this 3D array of shape `(1,1,5)`. Applying the first rule of broadcasting!

In [ ]:
h + [10, 20, 30, 40, 50]  # same as: h + [[[10, 20, 30, 40, 50]]]

## Second rule
*Arrays with a 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is repeated along that dimension.*

In [ ]:
k = np.arange(6).reshape(2, 3)
k

Let's try to add a 2D array of shape `(2,1)` to this 2D `ndarray` of shape `(2, 3)`. NumPy will apply the second rule of broadcasting:

In [ ]:
k + [[100], [200]]  # same as: k + [[100, 100, 100], [200, 200, 200]]

Combining rules 1 & 2, we can do this:

In [ ]:
k + [100, 200, 300]  # after rule 1: [[100, 200, 300]], and after rule 2: [[100, 200, 300], [100, 200, 300]]

## Third rule
*After rules 1 & 2, the sizes of all arrays must match.*

In [ ]:
try:
    k + [33, 44]
except ValueError as e:
    print(e)

Broadcasting rules are used in many NumPy operations, not just arithmetic operations, as we will see below.
For more details about broadcasting, check out [the documentation](https://docs.scipy.org/doc/numpy-dev/user/basics.broadcasting.html).

## Upcasting
When trying to combine arrays with different `dtype`s, NumPy will *upcast* to a type capable of handling all possible values (regardless of what the *actual* values are).

In [ ]:
k1 = np.arange(0, 5, dtype=np.uint8)
print(k1.dtype, k1)

In [ ]:
k2 = k1 + np.array([5, 6, 7, 8, 9], dtype=np.int8)
print(k2.dtype, k2)

Note that `int16` is required to represent all *possible* `int8` and `uint8` values (from -128 to 255), even though in this case a uint8 would have sufficed.

In [ ]:
k3 = k1 + 1.5
print(k3.dtype, k3)

# Conditional operators

The conditional operators also apply elementwise:

In [ ]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

And using broadcasting:

In [ ]:
m < 25  # equivalent to m < [25, 25, 25, 25]

This is most useful in conjunction with boolean indexing (discussed below).

In [ ]:
m[m < 25]

# Mathematical and statistical functions

Many mathematical and statistical functions are available for `ndarray`s.

## `ndarray` methods
Some functions are simply `ndarray` methods, for example:

In [ ]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("mean =", a.mean())

Note that this computes the mean of all elements in the `ndarray`, regardless of its shape.

Here are a few more useful `ndarray` methods:

In [ ]:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var):
    print(func.__name__, "=", func())

These functions accept an optional argument `axis` which lets you ask for the operation to be performed on elements along the given axis. For example:

In [ ]:
c=np.arange(24).reshape(2,3,4)
c

In [ ]:
c.sum(axis=0)  # sum across matrices

In [ ]:
c.sum(axis=1)  # sum across rows

You can also sum over multiple axes:

In [ ]:
c.sum(axis=(0,2))  # sum across matrices and columns

In [ ]:
0+1+2+3 + 12+13+14+15, 4+5+6+7 + 16+17+18+19, 8+9+10+11 + 20+21+22+23

## Universal functions
NumPy also provides fast elementwise functions called *universal functions*, or **ufunc**. They are vectorized wrappers of simple functions. For example `square` returns a new `ndarray` which is a copy of the original `ndarray` except that each element is squared:

In [ ]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

Here are a few more useful unary ufuncs:

In [ ]:
print("Original ndarray")
print(a)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))

## Binary ufuncs
There are also many binary ufuncs, that apply elementwise on two `ndarray`s.  Broadcasting rules are applied if the arrays do not have the same shape:

In [ ]:
a = np.array([1, -2, 3, 4])
b = np.array([2, 8, -1, 7])
np.add(a, b)  # equivalent to a + b

In [ ]:
np.greater(a, b)  # equivalent to a > b

In [ ]:
np.maximum(a, b)

In [ ]:
np.copysign(a, b)

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

In [ ]:
# One more example, try to find the differences
A = np.array([[1,1],[0,1]] )
B =np.array([[2,0],[3,4]] )
print(A*B)                         # elementwise product
print(A.dot(B))                  # matrix product
print(np.dot(A, B))             # another matrix product

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

You can find the full list of mathematical functions provided by numpy [in the documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

In [ ]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [ ]:
B = np.arange(3)
np.exp(B)

In [ ]:
np.sqrt(B)

In [ ]:
C = np.array([2., -1., 4.])
np.add(B, C)

Numpy provides many more functions for manipulating arrays; you can see the full list [in the documentation](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html).

### Reshape an Array

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [ ]:
a = np.floor(10*np.random.random((3,4)))
a

In [ ]:
a.ravel()  # returns the array, flattened

In [ ]:
a.reshape(6,2)  # returns the array with a modified shape

In [ ]:
a.T  # returns the array, transposed

In [ ]:
print(a.T.shape)
print(a.shape)

For more details about reshape function, please refer to the [documentation](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.reshape.html#numpy.reshape)

# Stacking arrays
It is often useful to stack together different arrays. NumPy offers several functions to do just that. Let's start by creating a few arrays.

Several arrays can be stacked together along different axes, i.e.,

In [ ]:
q1 = np.full((3,4), 1.0)
q1

In [ ]:
q2 = np.full((4,4), 2.0)
q2

In [ ]:
q3 = np.full((3,4), 3.0)
q3

## `vstack`
Now let's stack them vertically using `vstack`:

In [ ]:
q4 = np.vstack((q1, q2, q3))
q4

In [ ]:
q4.shape

This was possible because q1, q2 and q3 all have the same shape (except for the vertical axis, but that's ok since we are stacking on that axis).

## `hstack`
We can also stack arrays horizontally using `hstack`:

In [ ]:
q5 = np.hstack((q1, q3))
q5

In [ ]:
q5.shape

This is possible because q1 and q3 both have 3 rows. But since q2 has 4 rows, it cannot be stacked horizontally with q1 and q3:

In [ ]:
try:
    q5 = np.hstack((q1, q2, q3))
except ValueError as e:
    print(e)

## `concatenate`
The `concatenate` function stacks arrays along any given existing axis.

In [ ]:
q7 = np.concatenate((q1, q2, q3), axis=0)  # Equivalent to vstack
q7

In [ ]:
q7.shape

## `stack`
The `stack` function stacks arrays along a new axis. All arrays have to have the same shape.

In [ ]:
q8 = np.stack((q1, q3))
q8

# Splitting arrays
Splitting is the opposite of stacking. For example, let's use the `vsplit` function to split a matrix vertically.

First let's create a 6x4 matrix:

In [ ]:
r = np.arange(24).reshape(6,4)
r

Now let's split it in three equal parts, vertically:

In [ ]:
r1, r2, r3 = np.vsplit(r, 3)
r1

In [ ]:
r2

In [ ]:
r3

There is also a `split` function which splits an array along any given axis. Calling `vsplit` is equivalent to calling `split` with `axis=0`. There is also an `hsplit` function, equivalent to calling `split` with `axis=1`:

In [ ]:
r4, r5 = np.hsplit(r, 2)
r4

In [ ]:
r5

# Transposing arrays
The `transpose` method creates a new view on an `ndarray`'s data, with axes permuted in the given order.

For example, let's create a 3D array:

In [ ]:
t = np.arange(24).reshape(4,2,3)
t

Now let's create an `ndarray` such that the axes `0, 1, 2` (depth, height, width) are re-ordered to `1, 2, 0` (depth→width, height→depth, width→height):

In [ ]:
t1 = t.transpose((1,2,0))
t1

In [ ]:
t1.shape

By default, `transpose` reverses the order of the dimensions:

In [ ]:
t2 = t.transpose()  # equivalent to t.transpose((2, 1, 0))
t2

In [ ]:
t2.shape

NumPy provides a convenience function `swapaxes` to swap two axes. For example, let's create a new view of `t` with depth and height swapped:

In [ ]:
t3 = t.swapaxes(0,1)  # equivalent to t.transpose((1, 0, 2))
t3

In [ ]:
t3.shape

# Transposing arrays
The `transpose` method creates a new view on an `ndarray`'s data, with axes permuted in the given order.

For example, let's create a 3D array:

In [ ]:
t = np.arange(24).reshape(4,2,3)
t

Now let's create an `ndarray` such that the axes `0, 1, 2` (depth, height, width) are re-ordered to `1, 2, 0` (depth→width, height→depth, width→height):

In [ ]:
t1 = t.transpose((1,2,0))
t1

In [ ]:
t1.shape

By default, `transpose` reverses the order of the dimensions:

In [ ]:
t2 = t.transpose()  # equivalent to t.transpose((2, 1, 0))
t2

In [ ]:
t2.shape

NumPy provides a convenience function `swapaxes` to swap two axes. For example, let's create a new view of `t` with depth and height swapped:

In [ ]:
t3 = t.swapaxes(0,1)  # equivalent to t.transpose((1, 0, 2))
t3

In [ ]:
t3.shape

# Linear algebra
NumPy 2D arrays can be used to represent matrices efficiently in python. We will just quickly go through some of the main matrix operations available. For more details about Linear Algebra, vectors and matrics, go through the [Linear Algebra tutorial](math_linear_algebra.ipynb).

## Matrix transpose
The `T` attribute is equivalent to calling `transpose()` when the rank is ≥2:

In [ ]:
m1 = np.arange(10).reshape(2,5)
m1

In [ ]:
m1.T

The `T` attribute has no effect on rank 0 (empty) or rank 1 arrays:

In [ ]:
m2 = np.arange(5)
m2

In [ ]:
m2.T

We can get the desired transposition by first reshaping the 1D array to a single-row matrix (2D):

In [ ]:
m2r = m2.reshape(1,5)
m2r

In [ ]:
m2r.T

## Matrix dot product
Let's create two matrices and execute a matrix [dot product](https://en.wikipedia.org/wiki/Dot_product) using the `dot` method.

In [ ]:
n1 = np.arange(10).reshape(2, 5)
n1

In [ ]:
n2 = np.arange(15).reshape(5,3)
n2

In [ ]:
n1.dot(n2)

**Caution**: as mentionned previously, `n1*n2` is *not* a dot product, it is an elementwise product.

## Matrix inverse and pseudo-inverse
Many of the linear algebra functions are available in the `numpy.linalg` module, in particular the `inv` function to compute a square matrix's inverse:

In [ ]:
import numpy.linalg as linalg

m3 = np.array([[1,2,3],[5,7,11],[21,29,31]])
m3

In [ ]:
linalg.inv(m3)

You can also compute the [pseudoinverse](https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_pseudoinverse) using `pinv`:

In [ ]:
linalg.pinv(m3)

## Identity matrix
The product of a matrix by its inverse returns the identiy matrix (with small floating point errors):

In [ ]:
m3.dot(linalg.inv(m3))

You can create an identity matrix of size NxN by calling `eye`:

In [ ]:
np.eye(3)

## QR decomposition
The `qr` function computes the [QR decomposition](https://en.wikipedia.org/wiki/QR_decomposition) of a matrix:

In [ ]:
q, r = linalg.qr(m3)
q

In [ ]:
r

In [ ]:
q.dot(r)  # q.r equals m3

## Determinant
The `det` function computes the [matrix determinant](https://en.wikipedia.org/wiki/Determinant):

In [ ]:
linalg.det(m3)  # Computes the matrix determinant

## Eigenvalues and eigenvectors
The `eig` function computes the [eigenvalues and eigenvectors](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors) of a square matrix:

In [ ]:
eigenvalues, eigenvectors = linalg.eig(m3)
eigenvalues # λ

In [ ]:
eigenvectors # v

In [ ]:
m3.dot(eigenvectors) - eigenvalues * eigenvectors  # m3.v - λ*v = 0

## Singular Value Decomposition
The `svd` function takes a matrix and returns its [singular value decomposition](https://en.wikipedia.org/wiki/Singular_value_decomposition):

In [ ]:
m4 = np.array([[1,0,0,0,2], [0,0,3,0,0], [0,0,0,0,0], [0,2,0,0,0]])
m4

In [ ]:
U, S_diag, V = linalg.svd(m4)
U

In [ ]:
S_diag

The `svd` function just returns the values in the diagonal of Σ, but we want the full Σ matrix, so let's create it:

In [ ]:
S = np.zeros((4, 5))
S[np.diag_indices(4)] = S_diag
S  # Σ

In [ ]:
V

In [ ]:
U.dot(S).dot(V) # U.Σ.V == m4

## Diagonal and trace

In [ ]:
np.diag(m3)  # the values in the diagonal of m3 (top left to bottom right)

In [ ]:
np.trace(m3)  # equivalent to np.diag(m3).sum()

## Solving a system of linear scalar equations

The `solve` function solves a system of linear scalar equations, such as:

* $2x + 6y = 6$
* $5x + 3y = -9$

In [ ]:
coeffs  = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)
solution

Let's check the solution:

In [ ]:
coeffs.dot(solution), depvars  # yep, it's the same

Looks good! Another way to check the solution:

In [ ]:
np.allclose(coeffs.dot(solution), depvars)

# Vectorization
Instead of executing operations on individual array items, one at a time, your code is much more efficient if you try to stick to array operations. This is called *vectorization*. This way, you can benefit from NumPy's many optimizations.

For example, let's say we want to generate a 768x1024 array based on the formula $sin(xy/40.5)$. A **bad** option would be to do the math in python using nested loops:

In [ ]:
import math
data = np.empty((768, 1024))
for y in range(768):
    for x in range(1024):
        data[y, x] = math.sin(x*y/40.5)  # BAD! Very inefficient.

Sure, this works, but it's terribly inefficient since the loops are taking place in pure python. Let's vectorize this algorithm. First, we will use NumPy's `meshgrid` function which generates coordinate matrices from coordinate vectors.

In [ ]:
x_coords = np.arange(0, 1024)  # [0, 1, 2, ..., 1023]
y_coords = np.arange(0, 768)   # [0, 1, 2, ..., 767]
X, Y = np.meshgrid(x_coords, y_coords)
X

In [ ]:
Y

As you can see, both `X` and `Y` are 768x1024 arrays, and all values in `X` correspond to the horizontal coordinate, while all values in `Y` correspond to the the vertical coordinate.

Now we can simply compute the result using array operations:

In [ ]:
data = np.sin(X*Y/40.5)

Now we can plot this data using matplotlib's `imshow` function (see the [matplotlib tutorial](tools_matplotlib.ipynb)).

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.cm as cm
fig = plt.figure(1, figsize=(7, 6))
plt.imshow(data, cmap=cm.hot, interpolation="bicubic")
plt.show()

# Saving and loading
NumPy makes it easy to save and load `ndarray`s in binary or text format.

## Binary `.npy` format
Let's create a random array and save it.

In [ ]:
a = np.random.rand(2,3)
a

In [ ]:
np.save("my_array", a)

Done! Since the file name contains no file extension was provided, NumPy automatically added `.npy`. Let's take a peek at the file content:

In [ ]:
with open("my_array.npy", "rb") as f:
    content = f.read()

content

To load this file into a NumPy array, simply call `load`:

In [ ]:
a_loaded = np.load("my_array.npy")
a_loaded

## Text format
Let's try saving the array in text format:

In [ ]:
np.savetxt("my_array.csv", a)

Now let's look at the file content:

In [ ]:
with open("my_array.csv", "rt") as f:
    print(f.read())

This is a CSV file with tabs as delimiters. You can set a different delimiter:

In [ ]:
np.savetxt("my_array.csv", a, delimiter=",")

To load this file, just use `loadtxt`:

In [ ]:
a_loaded = np.loadtxt("my_array.csv", delimiter=",")
a_loaded

## Zipped `.npz` format
It is also possible to save multiple arrays in one zipped file:

In [ ]:
b = np.arange(24, dtype=np.uint8).reshape(2, 3, 4)
b

In [ ]:
np.savez("my_arrays", my_a=a, my_b=b)

Again, let's take a peek at the file content. Note that the `.npz` file extension was automatically added.

In [ ]:
with open("my_arrays.npz", "rb") as f:
    content = f.read()

repr(content)[:180] + "[...]"

You then load this file like so:

In [ ]:
my_arrays = np.load("my_arrays.npz")
my_arrays

In [ ]:
my_arrays.keys()

In [ ]:
my_arrays["my_a"]

### Some Useful Resources

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

For some basic operations of Numpy package, you can download the [Cheat Sheet for NumPy Basics](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

Large parts of this lab note originate from the following two resources:
[Quickstart tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)  and
[Python Numpy Tutorial](http://cs231n.github.io/python-numpy-tutorial/). Hereby, we acknowledge the contributors and developers for their efforts in providing these useful online resources.