# Reading and Writing Files in Python

In this section, we will learn some basic opearation about reading and writing files. Moreover, as a data scientist, building an accurate machine learning model is not the end of the project. We will showing you how to save and load your machine learning model in Python.This allows you to save your model to file and load it later in order to make predictions.

## Read txt file

In [4]:
txt_file_url = "../data/files/Python.txt"
f = open(txt_file_url, "r") #opens file with name of "Python.txt"
# read and print the entire file
print(f.read())
# remember to colse the file
f.close()

Life is short,
Use Python!


Used the **readline()** method twice, we would get the first 2 lines because of Python's reading process.

In [5]:
f = open(txt_file_url, "r") #opens file with name of "Python.txt"
# read the 1st line
print(f.readline())
# read the next line
print(f.readline())
f.close()

Life is short,

Use Python!


In [3]:
#opens file with name of "Python.txt"
f = open("files/Python.txt", "r") 
myList = []
for line in f:
    myList.append(line)
f.close()
    
print(myList)
print(myList[0])
print(myList[1])

['Life is short,\n', 'Use Python!']
Life is short,

Use Python!


## Write txt file

In [6]:
# Write file with name of "test.txt"
f = open("../data/files/test.txt","w")  
f.write("I love Python.\n")
f.write("I will be a Python master.\n")
f.write("I need to keep learning!")
f.close()

# read and see the test.txt file
f = open("../data/files/test.txt","r") 
print(f.read())
f.close()

I love Python.
I will be a Python master.
I need to keep learning!


## Read csv file

In [7]:
import csv
csvFile = open("../data/files/test.csv", "r") 
reader = csv.reader(csvFile, delimiter=',')
# load the data in a dictionary 
result = {}
for item in reader:
    # ignore the first line
    if reader.line_num == 1:
        continue    
    result[item[0]] = item[1]
csvFile.close()

print(result)    

{'Ali': '25', 'Bob': '24', 'Chirs': '29'}


## Write csv file

In [8]:
import csv
fileHeader = ["name", "age"]

d1 = ["Chris", "27"]
d2 = ["Ming", "26"]

csvFile = open("../data/files/write.csv", "w")
writer = csv.writer(csvFile)
writer = csv.writer(csvFile)

# write the head and data
writer.writerow(fileHeader)
writer.writerow(d1)
writer.writerow(d2)

# Here is another command 
# writer.writerows([fileHeader, d1, d2])

csvFile.close()

# go to see the "write.csv" file.

You can find more information from the [documentation](https://docs.python.org/3.6/library/csv.html)

## Using Pandas to Read CSV file

In [9]:
import pandas as pd
import numpy as np
data = pd.read_csv("../data/files/test.csv")
# data is data
print(data) 

# extract the age data
Age = np.array(data.Age, dtype = 'double')
print(Age)

# reshap this age vector
Age = np.reshape(Age, [3,1])
print(Age)

    Name  Age
0    Ali   25
1    Bob   24
2  Chirs   29
[25. 24. 29.]
[[25.]
 [24.]
 [29.]]


Find more operation about Pandas in the [documentation](https://pandas.pydata.org/) and [cheatsheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf)

## Read Matlab file

The functions --scipy.io.loadmat-- and --scipy.io.savemat-- allow you to read and write MATLAB files. You can read about them in the [documentation](https://docs.scipy.org/doc/scipy/reference/io.html).

In [10]:
import numpy as np
from scipy.io import loadmat, savemat

data = loadmat("../data/files/magic.mat");
print(data);
print(data['magic'])

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Sun Jan 28 21:23:19 2018', '__version__': '1.0', '__globals__': [], 'magic': array([[17, 24,  1,  8, 15],
       [23,  5,  7, 14, 16],
       [ 4,  6, 13, 20, 22],
       [10, 12, 19, 21,  3],
       [11, 18, 25,  2,  9]], dtype=uint8)}
[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]


## Write Matlab file

In [11]:
X = np.array(data['magic'])
# Do some calculation
X = X*2
# Dictionary from which to save matfile variables.
data = {'magic2': X}
# save the data
savemat("../data/files/magic2.mat", data)
# Go to matlab and check the data

data = loadmat("../data/files/magic2.mat");
print(data['magic2'])

[[34 48  2 16 30]
 [46 10 14 28 32]
 [ 8 12 26 40 44]
 [20 24 38 42  6]
 [22 36 50  4 18]]


## Save and Load file by Pickle

The Pickle pacakge is used for serializing and de-serializing a Python object structure. Any object in python can be pickled so that it can be saved on disk and loaded back to continue the work. 
You can read about them in the [documentation](https://docs.python.org/3.6/library/pickle.html?highlight=pickle#module-pickle).

In [12]:
import numpy as np
import pickle
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
# Save the matirx X
with open('../data/files/X.pickle', 'wb') as f:
    pickle.dump(X, f)
# Change the value of the original X    
X =  X + 4
print(X)

[[5. 4. 4. 4. 4.]
 [4. 5. 4. 4. 4.]
 [4. 4. 5. 4. 4.]
 [4. 4. 4. 5. 4.]
 [4. 4. 4. 4. 5.]]


In [12]:
# load the matrix 
with open('files/X.pickle', 'rb') as f:
    X = pickle.load(f)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# One Example 

In this demonstration, we will use a Logistic Regression Model and the Iris dataset.

In [15]:
from sklearn.linear_model import LogisticRegression  
from sklearn.datasets import load_iris  
from sklearn.model_selection import train_test_split

# Load and split data
data = load_iris()  
Xtrain, Xtest, Ytrain, Ytest = train_test_split(data.data, data.target, test_size=0.3, random_state=4)  

# Create a model
model = LogisticRegression(C=0.1,  
                           max_iter=2000, 
                           fit_intercept=True 
                           )
model.fit(Xtrain, Ytrain)  
print(model);

LogisticRegression(C=0.1, max_iter=2000)


In the following few lines of code, the model which we created in the previous step is saved to file, and then loaded as a new object called pickled_model. The loaded model is then used to calculate the accuracy score and predict outcomes on new unseen (test) data.

In [16]:
import pickle

#
# Create your model here (same as above)
#

# Save to file in the current working directory
pkl_filename = "../data/pickle_model.pkl"  
with open(pkl_filename, 'wb') as file:  
    pickle.dump(model, file)

# Load from file
with open(pkl_filename, 'rb') as file:  
    pickle_model = pickle.load(file)

# Calculate the accuracy score and predict target values
score = pickle_model.score(Xtest, Ytest)  
print("Test score: {0:.2f} %".format(100 * score))  
Ypredict = pickle_model.predict(Xtest)  

Test score: 97.78 %


Use python to read and write the `yaml` file.

In [18]:
import yaml
yaml_url = "../data/test.yaml"
with open(yaml_url, encoding='utf-8') as file:
    data = yaml.safe_load(file)
    print(data)
    print(data['case1']['json'])
    print(data['case1']['json']['username'])
 

{'case1': {'info': {'title': '正常登陆', 'url': 'http://192.168.1.1/user/login', 'method': 'POST'}, 'json': {'username': 'admin', 'password': '123456'}, 'expected': {'status_code': [200, 300], 'content': 'user_id'}}}
{'username': 'admin', 'password': '123456'}
admin


In [21]:
import yaml

content = {
    'id': 1,
    'text': 'programming languages',
    'members': ['java', 'python', 'python', 'c', 'go', 'shell'],
    'next': {'a':1,'b':2}
}

save_path = '../data/test_save.yaml'
with open(save_path, 'w', encoding='utf-8') as file:
    yaml.dump(content, file, default_flow_style=False, encoding='utf-8', allow_unicode=True)

with open(save_path, encoding='utf-8') as file:
    data = yaml.safe_load(file)
    print(data)

{'id': 1, 'members': ['java', 'python', 'python', 'c', 'go', 'shell'], 'next': {'a': 1, 'b': 2}, 'text': 'programming languages'}


In [22]:
# import pyyaml module
import yaml
from yaml.loader import SafeLoader

# Open the file and load the file
with open(save_path) as f:
    data = yaml.load(f, Loader=SafeLoader)
    print(data)

{'id': 1, 'members': ['java', 'python', 'python', 'c', 'go', 'shell'], 'next': {'a': 1, 'b': 2}, 'text': 'programming languages'}


In [23]:
import yaml

from yaml.loader import SafeLoader

with open(save_path, 'r') as f:
    data = list(yaml.load_all(f, Loader=SafeLoader))
    print(data)

[{'id': 1, 'members': ['java', 'python', 'python', 'c', 'go', 'shell'], 'next': {'a': 1, 'b': 2}, 'text': 'programming languages'}]


In [24]:
import yaml

# dict object
members = [{'name': 'Zoey', 'occupation': 'Doctor'},
           {'name': 'Zaara', 'occupation': 'Dentist'}]

# Convert Python dictionary into a YAML document
print(yaml.dump(members))

- name: Zoey
  occupation: Doctor
- name: Zaara
  occupation: Dentist



In [29]:
import yaml

save_path = '../data/model_config.yaml'

user_details = { 'model_name':'vgg19',
                'w1': [1, 2, 3, 4, 5.0],
                'AccessKeys': ['EmployeeTable',
                               'SoftwaresList',
                               'HardwareList']}

with open(save_path, 'w') as f:
    data = yaml.dump(user_details, f, sort_keys=False, default_flow_style=False)

with open(save_path, 'r') as f:
    # data = yaml.load_all(f, Loader=SafeLoader)
    data = yaml.safe_load(f)
    print(data)    

{'model_name': 'vgg19', 'w1': [1, 2, 3, 4, 5.0], 'AccessKeys': ['EmployeeTable', 'SoftwaresList', 'HardwareList']}


In [31]:
type(data['w1'])


list