# What is PyTorch?
It’s a Python-based scientific computing package targeted at two sets of audiences:
- A replacement for NumPy to use the power of GPUs
- a deep learning research platform that provides maximum flexibility and speed

## Getting Started
### Tensors
Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.7376e-42, 0.0000e+00],
        [0.0000e+00, 1.8014e+25, 0.0000e+00]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7864, 0.1845, 0.3651],
        [0.9607, 0.5186, 0.0457],
        [0.8015, 0.7517, 0.2393],
        [0.4493, 0.8398, 0.2132],
        [0.1539, 0.1670, 0.6811]])


Construct a matrix filled zeros and of dtype long:

In [5]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.5573,  1.1279, -0.6075],
        [ 1.0028,  1.0516, -1.2378],
        [ 0.6885, -0.0015,  0.4400],
        [ 0.2300,  1.4146,  1.4053],
        [-0.2209, -0.5555, -0.6465]])


Get its size:

In [8]:
print(x.size())

torch.Size([5, 3])


### Operations
There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.
Addition: syntax 1

In [9]:
y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# adds x to y
y.add_(x)
print(y)

tensor([[-1.0108,  1.9767, -0.2377],
        [ 1.5187,  1.5784, -0.5274],
        [ 1.1519,  0.9144,  1.3858],
        [ 0.6818,  2.2031,  1.7883],
        [ 0.7106,  0.0045, -0.4806]])
tensor([[-1.0108,  1.9767, -0.2377],
        [ 1.5187,  1.5784, -0.5274],
        [ 1.1519,  0.9144,  1.3858],
        [ 0.6818,  2.2031,  1.7883],
        [ 0.7106,  0.0045, -0.4806]])
tensor([[-1.0108,  1.9767, -0.2377],
        [ 1.5187,  1.5784, -0.5274],
        [ 1.1519,  0.9144,  1.3858],
        [ 0.6818,  2.2031,  1.7883],
        [ 0.7106,  0.0045, -0.4806]])
tensor([[-1.0108,  1.9767, -0.2377],
        [ 1.5187,  1.5784, -0.5274],
        [ 1.1519,  0.9144,  1.3858],
        [ 0.6818,  2.2031,  1.7883],
        [ 0.7106,  0.0045, -0.4806]])


You can use standard NumPy-like indexing with all bells and whistles!

In [10]:
print(x[:, 1])

tensor([ 1.1279,  1.0516, -0.0015,  1.4146, -0.5555])


Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [11]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions

print(x)
print(y)
print(z)

print(x.size(), y.size(), z.size())

tensor([[-0.5370, -1.1418,  0.3469,  0.0523],
        [-2.5647, -0.2751,  0.6323, -0.9384],
        [ 2.3960, -1.8664,  0.7196,  0.7527],
        [ 0.6154, -0.4833,  0.4970,  0.6009]])
tensor([-0.5370, -1.1418,  0.3469,  0.0523, -2.5647, -0.2751,  0.6323, -0.9384,
         2.3960, -1.8664,  0.7196,  0.7527,  0.6154, -0.4833,  0.4970,  0.6009])
tensor([[-0.5370, -1.1418,  0.3469,  0.0523, -2.5647, -0.2751,  0.6323, -0.9384],
        [ 2.3960, -1.8664,  0.7196,  0.7527,  0.6154, -0.4833,  0.4970,  0.6009]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [12]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.9043])
0.9043034911155701


## NumPy Bridge
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.
The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [13]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [14]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor
See how changing the np array changed the Torch Tensor automatically

In [15]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [16]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.9043], device='cuda:0')
tensor([1.9043], dtype=torch.float64)
